<?php

return [
    'dashboard' => [
        'label' => 'Dashboard',
        'icon' => 'fas fa-tachometer-alt',
        'route' => 'admin.dashboard',
        'active' => 'admin.dashboard',
    ],
    'homepage' => [
        'label' => 'Homepage',
        'icon' => 'fas fa-home',
        'route' => 'admin.homepage.index',
        'active' => 'admin.homepage.*',
    ],
    'products' => [
        'label' => 'Products',
        'icon' => 'fas fa-tshirt',
        'route' => 'admin.products.index',
        'active' => 'admin.products.*',
    ],
    'categories' => [
        'label' => 'Categories',
        'icon' => 'fas fa-tags',
        'route' => 'admin.categories.index',
        'active' => 'admin.categories.*',
    ],
    'users' => [
        'label' => 'Users',
        'icon' => 'fas fa-user-cog',
        'route' => 'admin.users.index',
        'active' => 'admin.users.*',
    ],
    'customers' => [
        'label' => 'Customers',
        'icon' => 'fas fa-users',
        'route' => 'admin.customers.index',
        'active' => 'admin.customers.*',
    ],
    'roles' => [
        'label' => 'Roles',
        'icon' => 'fas fa-user-shield',
        'route' => 'admin.roles.index',
        'active' => 'admin.roles.*',
    ],
    'orders' => [
        'label' => 'Order',
        'icon' => 'fas fa-shopping-cart',
        'route' => 'admin.orders.index',
        'active' => 'admin.orders.*',
    ],
    'orders_create' => [
        'label' => 'Create Order',
        'icon' => 'fas fa-plus',
        'route' => 'admin.orders.create',
        'active' => 'admin.orders.create',
        'permission' => 'orders',
    ],
    'orders_list' => [
        'label' => 'All Order',
        'icon' => 'fas fa-list',
        'route' => 'admin.orders.index',
        'active' => 'admin.orders.index|admin.orders.show|admin.orders.edit|admin.orders.invoice',
        'permission' => 'orders',
    ],
    'account_heads_list' => [
        'label' => 'Account Heads',
        'icon' => 'fas fa-list',
        'route' => 'admin.account-heads.index',
        'active' => 'admin.account-heads.*',
        'permission' => 'account_heads',
    ],
    'account_types_list' => [
        'label' => 'Account Types',
        'icon' => 'fas fa-tags',
        'route' => 'admin.account-types.index',
        'active' => 'admin.account-types.*',
        'permission' => 'account_heads',
    ],
    'coupons' => [
        'label' => 'Coupons',
        'icon' => 'fas fa-ticket-alt',
        'route' => 'admin.coupons.index',
        'active' => 'admin.coupons.*',
    ],
    'shipping' => [
        'label' => 'Shipping Fee (BDT)',
        'icon' => 'fas fa-truck',
        'route' => 'admin.shipping.edit',
        'active' => 'admin.shipping.*',
    ],
    'reports' => [
        'label' => 'Reports',
        'icon' => 'fas fa-chart-pie',
        'route' => 'admin.reports.index',
        'active' => 'admin.reports.*',
    ],
    'transactions' => [
        'label' => 'Transactions',
        'icon' => 'fas fa-money-check-alt',
        'route' => 'admin.transactions.index',
        'active' => 'admin.transactions.*',
    ],
    'payment_banks' => [
        'label' => 'Payment Banks',
        'icon' => 'fas fa-university',
        'route' => 'admin.payment-banks.index',
        'active' => 'admin.payment-banks.*',
    ],
    'bank_payments' => [
        'label' => 'Record Bank Payment',
        'icon' => 'fas fa-hand-holding-usd',
        'route' => 'admin.bank-payments.create',
        'active' => 'admin.bank-payments.*',
        'permission' => 'transactions',
    ],
    'customer_ledgers' => [
        'label' => 'Customer Ledger',
        'icon' => 'fas fa-book',
        'route' => 'admin.customer-ledgers.index',
        'active' => 'admin.customer-ledgers.*',
        'permission' => 'customers',
    ],
    'ssl_settings' => [
        'label' => 'SSL Settings',
        'icon' => 'fas fa-lock',
        'route' => 'admin.ssl-settings.edit',
        'active' => 'admin.ssl-settings.*',
        'permission' => 'settings',
    ],
    'order_api_settings' => [
        'label' => 'Order API Settings',
        'icon' => 'fas fa-shopping-bag',
        'route' => 'admin.orders.transfer-settings.edit',
        'active' => 'admin.orders.transfer-settings.*',
        'permission' => 'orders',
    ],
    'api_settings' => [
        'label' => 'Content API Settings',
        'icon' => 'fas fa-plug',
        'route' => 'admin.api-settings.index',
        'active' => 'admin.api-settings.*',
    ],
    'api_content' => [
        'label' => 'Import Product',
        'icon' => 'fas fa-images',
        'route' => 'admin.content.index',
        'active' => 'admin.content.*',
    ],
    'api_brands' => [
        'label' => 'Brands',
        'icon' => 'fas fa-copyright',
        'route' => 'admin.api-brands.index',
        'active' => 'admin.api-brands.*',
    ],
    'api_processed' => [
        'label' => 'Processed Product',
        'icon' => 'fas fa-check-circle',
        'route' => 'admin.processed.index',
        'active' => 'admin.processed.*',
    ],
    'storage_link' => [
        'label' => 'Storage Link',
        'icon' => 'fas fa-link',
        'route' => 'admin.storage-link.index',
        'active' => 'admin.storage-link.*',
    ],
    'terminal' => [
        'label' => 'Overview',
        'icon' => 'fas fa-terminal',
        'route' => 'admin.terminal.index',
        'active' => 'admin.terminal.*',
    ],
    'database_migration' => [
        'label' => 'Migration',
        'icon' => 'fas fa-database',
        'route' => 'admin.migration.index',
        'active' => 'admin.migration.*',
    ],
    'npm_build' => [
        'label' => 'NPM Build',
        'icon' => 'fas fa-code',
        'route' => 'admin.frontend-build.index',
        'active' => 'admin.frontend-build.*',
    ],
    'settings' => [
        'label' => 'Settings',
        'icon' => 'fas fa-cog',
        'route' => 'admin.settings.branding.edit',
        'active' => 'admin.settings.*',
    ],
    'settings_branding' => [
        'label' => 'Branding',
        'icon' => 'fas fa-paint-brush',
        'route' => 'admin.settings.branding.edit',
        'active' => 'admin.settings.branding.*',
        'permission' => 'settings',
    ],
    'settings_footer' => [
        'label' => 'Footer',
        'icon' => 'fas fa-shoe-prints',
        'route' => 'admin.settings.footer.edit',
        'active' => 'admin.settings.footer.*',
        'permission' => 'settings',
    ],
    'settings_top_bar' => [
        'label' => 'Top Bar',
        'icon' => 'fas fa-bars',
        'route' => 'admin.settings.top_bar.edit',
        'active' => 'admin.settings.top_bar.*',
        'permission' => 'settings',
    ],
    'settings_website_colors' => [
        'label' => 'Website Colors',
        'icon' => 'fas fa-palette',
        'route' => 'admin.settings.website_colors.edit',
        'active' => 'admin.settings.website_colors.*',
        'permission' => 'settings',
    ],
    'settings_gtm' => [
        'label' => 'Google Tag Manager',
        'icon' => 'fab fa-google',
        'route' => 'admin.settings.gtm.edit',
        'active' => 'admin.settings.gtm.*',
        'permission' => 'settings',
    ],
];
